---
# tasks file for vector
- name: Download vector packages
  get_url:
    url: "{{ vector_url }}"
    dest: "/opt/vector-{{ vector_version }}-1.x86_64.rpm"
- name: Install vector
  yum:
    name: "/opt/vector-{{ vector_version }}-1.x86_64.rpm"
    disable_gpg_check: true
- name: Apply conf template
  template:
    src: vector.yml.j2
    dest: "{{ vector_config_dir }}/vector.yml"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
- name: Change systemd unit
  template:
    src: vector.service.j2
    dest: /usr/lib/systemd/system/vector.service
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    backup: true
  notify: Start Vector service